package com.yangfan.labor.repository;

import com.yangfan.labor.entity.OubShipmentDetail;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface OubShipmentDetailMapper {
    @Delete({
        "delete from oub_shipment_detail",
        "where oub_shipment_detail_id = #{oubShipmentDetailId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long oubShipmentDetailId);

    @Insert({
        "insert into oub_shipment_detail (oub_shipment_header_id, shipment_no, ",
        "shipment_line_no, warehouse_code, ",
        "status_code, erp_order_no, ",
        "erp_order_line_no, item_code, ",
        "item_name, client_code, ",
        "client_name, inventory_type, ",
        "batch_no, inventory_quality, ",
        "country_of_origin, exp_date, ",
        "mfg_date, received_date, ",
        "po_no, sales_no, sales_status, ",
        "inventory_status, brand_code, ",
        "brand_name, vendor_code, ",
        "vendor_name, req_qty, ",
        "req_uom, orig_allocation_qty, ",
        "allocation_qty, allocation_uom, ",
        "picked_qty, picked_uom, ",
        "oqc_qty, oqc_uom, ",
        "sorting_qty, sorting_ep_qty, ",
        "sorting_uom, oub_qty, ",
        "oub_uom, oub_date, ",
        "oub_user, priority, ",
        "exception_type, exception_desc, ",
        "exception_approach, exception_qty, ",
        "price, item_retail_price, ",
        "item_net_price, req_weight, ",
        "weight_uom, item_class_code, ",
        "is_gift, is_immediate_need, ",
        "ec_mode, req_volume, ",
        "req_volume_uom, brand_type, ",
        "channel_type, fulfillment_type, ",
        "item_size, package_code, ",
        "package_name, return_max_uom, ",
        "return_max_qty, oqc_itemscan_field1, ",
        "oqc_itemscan_value1, oqc_itemscan_field2, ",
        "oqc_itemscan_value2, oqc_column_field1, ",
        "oqc_column_value1, oqc_column_field2, ",
        "oqc_column_value2, oqc_itemdesc_value1, ",
        "oqc_itemdesc_value2, no_po, ",
        "en_company_desc, en_item_desc, ",
        "gross_weight, sale_brand_id, ",
        "reserved_qty, inv_lot_id, ",
        "lot_attr1, lot_attr2, ",
        "lot_attr3, lot_attr4, ",
        "lot_attr5, lot_attr6, ",
        "lot_attr7, lot_attr8, ",
        "lot_attr9, lot_attr10, ",
        "lot_attr11, lot_attr12, ",
        "lot_attr13, lot_attr14, ",
        "lot_attr15, lot_attr16, ",
        "user_def1, user_def2, ",
        "user_def3, user_def4, ",
        "user_def5, user_def6, ",
        "user_def7, user_def8, ",
        "user_def9, user_def10, ",
        "goods_line_money, from_warehouse_code, ",
        "goods_pic, created_by_user_id, ",
        "created_by_user, created_office, ",
        "created_dtm_loc, created_time_zone, ",
        "updated_by_user_id, updated_by_user, ",
        "updated_office, updated_dtm_loc, ",
        "updated_time_zone, record_version, ",
        "container_code, owner_code, ",
        "sales_type_flag, not_allow_return, ",
        "inventory_group, serial_no)",
        "values (#{oubShipmentHeaderId,jdbcType=BIGINT}, #{shipmentNo,jdbcType=VARCHAR}, ",
        "#{shipmentLineNo,jdbcType=INTEGER}, #{warehouseCode,jdbcType=VARCHAR}, ",
        "#{statusCode,jdbcType=SMALLINT}, #{erpOrderNo,jdbcType=VARCHAR}, ",
        "#{erpOrderLineNo,jdbcType=VARCHAR}, #{itemCode,jdbcType=VARCHAR}, ",
        "#{itemName,jdbcType=VARCHAR}, #{clientCode,jdbcType=VARCHAR}, ",
        "#{clientName,jdbcType=VARCHAR}, #{inventoryType,jdbcType=VARCHAR}, ",
        "#{batchNo,jdbcType=VARCHAR}, #{inventoryQuality,jdbcType=VARCHAR}, ",
        "#{countryOfOrigin,jdbcType=VARCHAR}, #{expDate,jdbcType=DATE}, ",
        "#{mfgDate,jdbcType=DATE}, #{receivedDate,jdbcType=DATE}, ",
        "#{poNo,jdbcType=VARCHAR}, #{salesNo,jdbcType=VARCHAR}, #{salesStatus,jdbcType=VARCHAR}, ",
        "#{inventoryStatus,jdbcType=BIT}, #{brandCode,jdbcType=VARCHAR}, ",
        "#{brandName,jdbcType=VARCHAR}, #{vendorCode,jdbcType=VARCHAR}, ",
        "#{vendorName,jdbcType=VARCHAR}, #{reqQty,jdbcType=DECIMAL}, ",
        "#{reqUom,jdbcType=VARCHAR}, #{origAllocationQty,jdbcType=DECIMAL}, ",
        "#{allocationQty,jdbcType=DECIMAL}, #{allocationUom,jdbcType=VARCHAR}, ",
        "#{pickedQty,jdbcType=DECIMAL}, #{pickedUom,jdbcType=VARCHAR}, ",
        "#{oqcQty,jdbcType=DECIMAL}, #{oqcUom,jdbcType=VARCHAR}, ",
        "#{sortingQty,jdbcType=DECIMAL}, #{sortingEpQty,jdbcType=DECIMAL}, ",
        "#{sortingUom,jdbcType=VARCHAR}, #{oubQty,jdbcType=DECIMAL}, ",
        "#{oubUom,jdbcType=VARCHAR}, #{oubDate,jdbcType=TIMESTAMP}, ",
        "#{oubUser,jdbcType=VARCHAR}, #{priority,jdbcType=VARCHAR}, ",
        "#{exceptionType,jdbcType=VARCHAR}, #{exceptionDesc,jdbcType=VARCHAR}, ",
        "#{exceptionApproach,jdbcType=VARCHAR}, #{exceptionQty,jdbcType=DECIMAL}, ",
        "#{price,jdbcType=DECIMAL}, #{itemRetailPrice,jdbcType=DECIMAL}, ",
        "#{itemNetPrice,jdbcType=DECIMAL}, #{reqWeight,jdbcType=DECIMAL}, ",
        "#{weightUom,jdbcType=VARCHAR}, #{itemClassCode,jdbcType=VARCHAR}, ",
        "#{isGift,jdbcType=BIT}, #{isImmediateNeed,jdbcType=BIT}, ",
        "#{ecMode,jdbcType=VARCHAR}, #{reqVolume,jdbcType=DECIMAL}, ",
        "#{reqVolumeUom,jdbcType=VARCHAR}, #{brandType,jdbcType=VARCHAR}, ",
        "#{channelType,jdbcType=VARCHAR}, #{fulfillmentType,jdbcType=VARCHAR}, ",
        "#{itemSize,jdbcType=VARCHAR}, #{packageCode,jdbcType=VARCHAR}, ",
        "#{packageName,jdbcType=VARCHAR}, #{returnMaxUom,jdbcType=VARCHAR}, ",
        "#{returnMaxQty,jdbcType=DECIMAL}, #{oqcItemscanField1,jdbcType=VARCHAR}, ",
        "#{oqcItemscanValue1,jdbcType=VARCHAR}, #{oqcItemscanField2,jdbcType=VARCHAR}, ",
        "#{oqcItemscanValue2,jdbcType=VARCHAR}, #{oqcColumnField1,jdbcType=VARCHAR}, ",
        "#{oqcColumnValue1,jdbcType=VARCHAR}, #{oqcColumnField2,jdbcType=VARCHAR}, ",
        "#{oqcColumnValue2,jdbcType=VARCHAR}, #{oqcItemdescValue1,jdbcType=VARCHAR}, ",
        "#{oqcItemdescValue2,jdbcType=VARCHAR}, #{noPo,jdbcType=SMALLINT}, ",
        "#{enCompanyDesc,jdbcType=VARCHAR}, #{enItemDesc,jdbcType=VARCHAR}, ",
        "#{grossWeight,jdbcType=DECIMAL}, #{saleBrandId,jdbcType=VARCHAR}, ",
        "#{reservedQty,jdbcType=DECIMAL}, #{invLotId,jdbcType=BIGINT}, ",
        "#{lotAttr1,jdbcType=VARCHAR}, #{lotAttr2,jdbcType=VARCHAR}, ",
        "#{lotAttr3,jdbcType=VARCHAR}, #{lotAttr4,jdbcType=VARCHAR}, ",
        "#{lotAttr5,jdbcType=VARCHAR}, #{lotAttr6,jdbcType=VARCHAR}, ",
        "#{lotAttr7,jdbcType=VARCHAR}, #{lotAttr8,jdbcType=VARCHAR}, ",
        "#{lotAttr9,jdbcType=DECIMAL}, #{lotAttr10,jdbcType=DECIMAL}, ",
        "#{lotAttr11,jdbcType=DECIMAL}, #{lotAttr12,jdbcType=DECIMAL}, ",
        "#{lotAttr13,jdbcType=DATE}, #{lotAttr14,jdbcType=DATE}, ",
        "#{lotAttr15,jdbcType=DATE}, #{lotAttr16,jdbcType=DATE}, ",
        "#{userDef1,jdbcType=VARCHAR}, #{userDef2,jdbcType=VARCHAR}, ",
        "#{userDef3,jdbcType=VARCHAR}, #{userDef4,jdbcType=VARCHAR}, ",
        "#{userDef5,jdbcType=VARCHAR}, #{userDef6,jdbcType=VARCHAR}, ",
        "#{userDef7,jdbcType=TIMESTAMP}, #{userDef8,jdbcType=TIMESTAMP}, ",
        "#{userDef9,jdbcType=DECIMAL}, #{userDef10,jdbcType=DECIMAL}, ",
        "#{goodsLineMoney,jdbcType=DECIMAL}, #{fromWarehouseCode,jdbcType=VARCHAR}, ",
        "#{goodsPic,jdbcType=VARCHAR}, #{createdByUserId,jdbcType=BIGINT}, ",
        "#{createdByUser,jdbcType=VARCHAR}, #{createdOffice,jdbcType=VARCHAR}, ",
        "#{createdDtmLoc,jdbcType=TIMESTAMP}, #{createdTimeZone,jdbcType=VARCHAR}, ",
        "#{updatedByUserId,jdbcType=BIGINT}, #{updatedByUser,jdbcType=VARCHAR}, ",
        "#{updatedOffice,jdbcType=VARCHAR}, #{updatedDtmLoc,jdbcType=TIMESTAMP}, ",
        "#{updatedTimeZone,jdbcType=VARCHAR}, #{recordVersion,jdbcType=BIGINT}, ",
        "#{containerCode,jdbcType=VARCHAR}, #{ownerCode,jdbcType=VARCHAR}, ",
        "#{salesTypeFlag,jdbcType=TINYINT}, #{notAllowReturn,jdbcType=TINYINT}, ",
        "#{inventoryGroup,jdbcType=TINYINT}, #{serialNo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="oubShipmentDetailId", before=false, resultType=Long.class)
    int insert(OubShipmentDetail record);

    @Select({
        "select",
        "oub_shipment_detail_id, oub_shipment_header_id, shipment_no, shipment_line_no, ",
        "warehouse_code, status_code, erp_order_no, erp_order_line_no, item_code, item_name, ",
        "client_code, client_name, inventory_type, batch_no, inventory_quality, country_of_origin, ",
        "exp_date, mfg_date, received_date, po_no, sales_no, sales_status, inventory_status, ",
        "brand_code, brand_name, vendor_code, vendor_name, req_qty, req_uom, orig_allocation_qty, ",
        "allocation_qty, allocation_uom, picked_qty, picked_uom, oqc_qty, oqc_uom, sorting_qty, ",
        "sorting_ep_qty, sorting_uom, oub_qty, oub_uom, oub_date, oub_user, priority, ",
        "exception_type, exception_desc, exception_approach, exception_qty, price, item_retail_price, ",
        "item_net_price, req_weight, weight_uom, item_class_code, is_gift, is_immediate_need, ",
        "ec_mode, req_volume, req_volume_uom, brand_type, channel_type, fulfillment_type, ",
        "item_size, package_code, package_name, return_max_uom, return_max_qty, oqc_itemscan_field1, ",
        "oqc_itemscan_value1, oqc_itemscan_field2, oqc_itemscan_value2, oqc_column_field1, ",
        "oqc_column_value1, oqc_column_field2, oqc_column_value2, oqc_itemdesc_value1, ",
        "oqc_itemdesc_value2, no_po, en_company_desc, en_item_desc, gross_weight, sale_brand_id, ",
        "reserved_qty, inv_lot_id, lot_attr1, lot_attr2, lot_attr3, lot_attr4, lot_attr5, ",
        "lot_attr6, lot_attr7, lot_attr8, lot_attr9, lot_attr10, lot_attr11, lot_attr12, ",
        "lot_attr13, lot_attr14, lot_attr15, lot_attr16, user_def1, user_def2, user_def3, ",
        "user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, ",
        "goods_line_money, from_warehouse_code, goods_pic, created_by_user_id, created_by_user, ",
        "created_office, created_dtm_loc, created_time_zone, updated_by_user_id, updated_by_user, ",
        "updated_office, updated_dtm_loc, updated_time_zone, record_version, container_code, ",
        "owner_code, sales_type_flag, not_allow_return, inventory_group, serial_no",
        "from oub_shipment_detail",
        "where oub_shipment_detail_id = #{oubShipmentDetailId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="oub_shipment_detail_id", property="oubShipmentDetailId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="oub_shipment_header_id", property="oubShipmentHeaderId", jdbcType=JdbcType.BIGINT),
        @Result(column="shipment_no", property="shipmentNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shipment_line_no", property="shipmentLineNo", jdbcType=JdbcType.INTEGER),
        @Result(column="warehouse_code", property="warehouseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="status_code", property="statusCode", jdbcType=JdbcType.SMALLINT),
        @Result(column="erp_order_no", property="erpOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="erp_order_line_no", property="erpOrderLineNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_code", property="itemCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_name", property="itemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_code", property="clientCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_name", property="clientName", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_type", property="inventoryType", jdbcType=JdbcType.VARCHAR),
        @Result(column="batch_no", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_quality", property="inventoryQuality", jdbcType=JdbcType.VARCHAR),
        @Result(column="country_of_origin", property="countryOfOrigin", jdbcType=JdbcType.VARCHAR),
        @Result(column="exp_date", property="expDate", jdbcType=JdbcType.DATE),
        @Result(column="mfg_date", property="mfgDate", jdbcType=JdbcType.DATE),
        @Result(column="received_date", property="receivedDate", jdbcType=JdbcType.DATE),
        @Result(column="po_no", property="poNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_no", property="salesNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_status", property="salesStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_status", property="inventoryStatus", jdbcType=JdbcType.BIT),
        @Result(column="brand_code", property="brandCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="vendor_code", property="vendorCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="vendor_name", property="vendorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="req_qty", property="reqQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_uom", property="reqUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="orig_allocation_qty", property="origAllocationQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="allocation_qty", property="allocationQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="allocation_uom", property="allocationUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="picked_qty", property="pickedQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="picked_uom", property="pickedUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_qty", property="oqcQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oqc_uom", property="oqcUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="sorting_qty", property="sortingQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="sorting_ep_qty", property="sortingEpQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="sorting_uom", property="sortingUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oub_qty", property="oubQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oub_uom", property="oubUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oub_date", property="oubDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="oub_user", property="oubUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_type", property="exceptionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_desc", property="exceptionDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_approach", property="exceptionApproach", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_qty", property="exceptionQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="item_retail_price", property="itemRetailPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="item_net_price", property="itemNetPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_weight", property="reqWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight_uom", property="weightUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_class_code", property="itemClassCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_gift", property="isGift", jdbcType=JdbcType.BIT),
        @Result(column="is_immediate_need", property="isImmediateNeed", jdbcType=JdbcType.BIT),
        @Result(column="ec_mode", property="ecMode", jdbcType=JdbcType.VARCHAR),
        @Result(column="req_volume", property="reqVolume", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_volume_uom", property="reqVolumeUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_type", property="brandType", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_type", property="channelType", jdbcType=JdbcType.VARCHAR),
        @Result(column="fulfillment_type", property="fulfillmentType", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_size", property="itemSize", jdbcType=JdbcType.VARCHAR),
        @Result(column="package_code", property="packageCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="package_name", property="packageName", jdbcType=JdbcType.VARCHAR),
        @Result(column="return_max_uom", property="returnMaxUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="return_max_qty", property="returnMaxQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oqc_itemscan_field1", property="oqcItemscanField1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_value1", property="oqcItemscanValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_field2", property="oqcItemscanField2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_value2", property="oqcItemscanValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_field1", property="oqcColumnField1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_value1", property="oqcColumnValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_field2", property="oqcColumnField2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_value2", property="oqcColumnValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemdesc_value1", property="oqcItemdescValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemdesc_value2", property="oqcItemdescValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="no_po", property="noPo", jdbcType=JdbcType.SMALLINT),
        @Result(column="en_company_desc", property="enCompanyDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="en_item_desc", property="enItemDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="gross_weight", property="grossWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="sale_brand_id", property="saleBrandId", jdbcType=JdbcType.VARCHAR),
        @Result(column="reserved_qty", property="reservedQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="inv_lot_id", property="invLotId", jdbcType=JdbcType.BIGINT),
        @Result(column="lot_attr1", property="lotAttr1", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr2", property="lotAttr2", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr3", property="lotAttr3", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr4", property="lotAttr4", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr5", property="lotAttr5", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr6", property="lotAttr6", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr7", property="lotAttr7", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr8", property="lotAttr8", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr9", property="lotAttr9", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr10", property="lotAttr10", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr11", property="lotAttr11", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr12", property="lotAttr12", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr13", property="lotAttr13", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr14", property="lotAttr14", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr15", property="lotAttr15", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr16", property="lotAttr16", jdbcType=JdbcType.DATE),
        @Result(column="user_def1", property="userDef1", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def2", property="userDef2", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def3", property="userDef3", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def4", property="userDef4", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def5", property="userDef5", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def6", property="userDef6", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def7", property="userDef7", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_def8", property="userDef8", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_def9", property="userDef9", jdbcType=JdbcType.DECIMAL),
        @Result(column="user_def10", property="userDef10", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_line_money", property="goodsLineMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="from_warehouse_code", property="fromWarehouseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_pic", property="goodsPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_id", property="createdByUserId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_by_user", property="createdByUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_office", property="createdOffice", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_dtm_loc", property="createdDtmLoc", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_time_zone", property="createdTimeZone", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_by_user_id", property="updatedByUserId", jdbcType=JdbcType.BIGINT),
        @Result(column="updated_by_user", property="updatedByUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_office", property="updatedOffice", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_dtm_loc", property="updatedDtmLoc", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_time_zone", property="updatedTimeZone", jdbcType=JdbcType.VARCHAR),
        @Result(column="record_version", property="recordVersion", jdbcType=JdbcType.BIGINT),
        @Result(column="container_code", property="containerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="owner_code", property="ownerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_type_flag", property="salesTypeFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="not_allow_return", property="notAllowReturn", jdbcType=JdbcType.TINYINT),
        @Result(column="inventory_group", property="inventoryGroup", jdbcType=JdbcType.TINYINT),
        @Result(column="serial_no", property="serialNo", jdbcType=JdbcType.VARCHAR)
    })
    OubShipmentDetail selectByPrimaryKey(Long oubShipmentDetailId);

    @Select({
        "select",
        "oub_shipment_detail_id, oub_shipment_header_id, shipment_no, shipment_line_no, ",
        "warehouse_code, status_code, erp_order_no, erp_order_line_no, item_code, item_name, ",
        "client_code, client_name, inventory_type, batch_no, inventory_quality, country_of_origin, ",
        "exp_date, mfg_date, received_date, po_no, sales_no, sales_status, inventory_status, ",
        "brand_code, brand_name, vendor_code, vendor_name, req_qty, req_uom, orig_allocation_qty, ",
        "allocation_qty, allocation_uom, picked_qty, picked_uom, oqc_qty, oqc_uom, sorting_qty, ",
        "sorting_ep_qty, sorting_uom, oub_qty, oub_uom, oub_date, oub_user, priority, ",
        "exception_type, exception_desc, exception_approach, exception_qty, price, item_retail_price, ",
        "item_net_price, req_weight, weight_uom, item_class_code, is_gift, is_immediate_need, ",
        "ec_mode, req_volume, req_volume_uom, brand_type, channel_type, fulfillment_type, ",
        "item_size, package_code, package_name, return_max_uom, return_max_qty, oqc_itemscan_field1, ",
        "oqc_itemscan_value1, oqc_itemscan_field2, oqc_itemscan_value2, oqc_column_field1, ",
        "oqc_column_value1, oqc_column_field2, oqc_column_value2, oqc_itemdesc_value1, ",
        "oqc_itemdesc_value2, no_po, en_company_desc, en_item_desc, gross_weight, sale_brand_id, ",
        "reserved_qty, inv_lot_id, lot_attr1, lot_attr2, lot_attr3, lot_attr4, lot_attr5, ",
        "lot_attr6, lot_attr7, lot_attr8, lot_attr9, lot_attr10, lot_attr11, lot_attr12, ",
        "lot_attr13, lot_attr14, lot_attr15, lot_attr16, user_def1, user_def2, user_def3, ",
        "user_def4, user_def5, user_def6, user_def7, user_def8, user_def9, user_def10, ",
        "goods_line_money, from_warehouse_code, goods_pic, created_by_user_id, created_by_user, ",
        "created_office, created_dtm_loc, created_time_zone, updated_by_user_id, updated_by_user, ",
        "updated_office, updated_dtm_loc, updated_time_zone, record_version, container_code, ",
        "owner_code, sales_type_flag, not_allow_return, inventory_group, serial_no",
        "from oub_shipment_detail"
    })
    @Results({
        @Result(column="oub_shipment_detail_id", property="oubShipmentDetailId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="oub_shipment_header_id", property="oubShipmentHeaderId", jdbcType=JdbcType.BIGINT),
        @Result(column="shipment_no", property="shipmentNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="shipment_line_no", property="shipmentLineNo", jdbcType=JdbcType.INTEGER),
        @Result(column="warehouse_code", property="warehouseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="status_code", property="statusCode", jdbcType=JdbcType.SMALLINT),
        @Result(column="erp_order_no", property="erpOrderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="erp_order_line_no", property="erpOrderLineNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_code", property="itemCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_name", property="itemName", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_code", property="clientCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_name", property="clientName", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_type", property="inventoryType", jdbcType=JdbcType.VARCHAR),
        @Result(column="batch_no", property="batchNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_quality", property="inventoryQuality", jdbcType=JdbcType.VARCHAR),
        @Result(column="country_of_origin", property="countryOfOrigin", jdbcType=JdbcType.VARCHAR),
        @Result(column="exp_date", property="expDate", jdbcType=JdbcType.DATE),
        @Result(column="mfg_date", property="mfgDate", jdbcType=JdbcType.DATE),
        @Result(column="received_date", property="receivedDate", jdbcType=JdbcType.DATE),
        @Result(column="po_no", property="poNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_no", property="salesNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_status", property="salesStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="inventory_status", property="inventoryStatus", jdbcType=JdbcType.BIT),
        @Result(column="brand_code", property="brandCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_name", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="vendor_code", property="vendorCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="vendor_name", property="vendorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="req_qty", property="reqQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_uom", property="reqUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="orig_allocation_qty", property="origAllocationQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="allocation_qty", property="allocationQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="allocation_uom", property="allocationUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="picked_qty", property="pickedQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="picked_uom", property="pickedUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_qty", property="oqcQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oqc_uom", property="oqcUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="sorting_qty", property="sortingQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="sorting_ep_qty", property="sortingEpQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="sorting_uom", property="sortingUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oub_qty", property="oubQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oub_uom", property="oubUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="oub_date", property="oubDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="oub_user", property="oubUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_type", property="exceptionType", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_desc", property="exceptionDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_approach", property="exceptionApproach", jdbcType=JdbcType.VARCHAR),
        @Result(column="exception_qty", property="exceptionQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="item_retail_price", property="itemRetailPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="item_net_price", property="itemNetPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_weight", property="reqWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="weight_uom", property="weightUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_class_code", property="itemClassCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_gift", property="isGift", jdbcType=JdbcType.BIT),
        @Result(column="is_immediate_need", property="isImmediateNeed", jdbcType=JdbcType.BIT),
        @Result(column="ec_mode", property="ecMode", jdbcType=JdbcType.VARCHAR),
        @Result(column="req_volume", property="reqVolume", jdbcType=JdbcType.DECIMAL),
        @Result(column="req_volume_uom", property="reqVolumeUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_type", property="brandType", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_type", property="channelType", jdbcType=JdbcType.VARCHAR),
        @Result(column="fulfillment_type", property="fulfillmentType", jdbcType=JdbcType.VARCHAR),
        @Result(column="item_size", property="itemSize", jdbcType=JdbcType.VARCHAR),
        @Result(column="package_code", property="packageCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="package_name", property="packageName", jdbcType=JdbcType.VARCHAR),
        @Result(column="return_max_uom", property="returnMaxUom", jdbcType=JdbcType.VARCHAR),
        @Result(column="return_max_qty", property="returnMaxQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="oqc_itemscan_field1", property="oqcItemscanField1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_value1", property="oqcItemscanValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_field2", property="oqcItemscanField2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemscan_value2", property="oqcItemscanValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_field1", property="oqcColumnField1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_value1", property="oqcColumnValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_field2", property="oqcColumnField2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_column_value2", property="oqcColumnValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemdesc_value1", property="oqcItemdescValue1", jdbcType=JdbcType.VARCHAR),
        @Result(column="oqc_itemdesc_value2", property="oqcItemdescValue2", jdbcType=JdbcType.VARCHAR),
        @Result(column="no_po", property="noPo", jdbcType=JdbcType.SMALLINT),
        @Result(column="en_company_desc", property="enCompanyDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="en_item_desc", property="enItemDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="gross_weight", property="grossWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="sale_brand_id", property="saleBrandId", jdbcType=JdbcType.VARCHAR),
        @Result(column="reserved_qty", property="reservedQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="inv_lot_id", property="invLotId", jdbcType=JdbcType.BIGINT),
        @Result(column="lot_attr1", property="lotAttr1", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr2", property="lotAttr2", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr3", property="lotAttr3", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr4", property="lotAttr4", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr5", property="lotAttr5", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr6", property="lotAttr6", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr7", property="lotAttr7", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr8", property="lotAttr8", jdbcType=JdbcType.VARCHAR),
        @Result(column="lot_attr9", property="lotAttr9", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr10", property="lotAttr10", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr11", property="lotAttr11", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr12", property="lotAttr12", jdbcType=JdbcType.DECIMAL),
        @Result(column="lot_attr13", property="lotAttr13", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr14", property="lotAttr14", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr15", property="lotAttr15", jdbcType=JdbcType.DATE),
        @Result(column="lot_attr16", property="lotAttr16", jdbcType=JdbcType.DATE),
        @Result(column="user_def1", property="userDef1", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def2", property="userDef2", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def3", property="userDef3", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def4", property="userDef4", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def5", property="userDef5", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def6", property="userDef6", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_def7", property="userDef7", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_def8", property="userDef8", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_def9", property="userDef9", jdbcType=JdbcType.DECIMAL),
        @Result(column="user_def10", property="userDef10", jdbcType=JdbcType.DECIMAL),
        @Result(column="goods_line_money", property="goodsLineMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="from_warehouse_code", property="fromWarehouseCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_pic", property="goodsPic", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_by_user_id", property="createdByUserId", jdbcType=JdbcType.BIGINT),
        @Result(column="created_by_user", property="createdByUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_office", property="createdOffice", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_dtm_loc", property="createdDtmLoc", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="created_time_zone", property="createdTimeZone", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_by_user_id", property="updatedByUserId", jdbcType=JdbcType.BIGINT),
        @Result(column="updated_by_user", property="updatedByUser", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_office", property="updatedOffice", jdbcType=JdbcType.VARCHAR),
        @Result(column="updated_dtm_loc", property="updatedDtmLoc", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_time_zone", property="updatedTimeZone", jdbcType=JdbcType.VARCHAR),
        @Result(column="record_version", property="recordVersion", jdbcType=JdbcType.BIGINT),
        @Result(column="container_code", property="containerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="owner_code", property="ownerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="sales_type_flag", property="salesTypeFlag", jdbcType=JdbcType.TINYINT),
        @Result(column="not_allow_return", property="notAllowReturn", jdbcType=JdbcType.TINYINT),
        @Result(column="inventory_group", property="inventoryGroup", jdbcType=JdbcType.TINYINT),
        @Result(column="serial_no", property="serialNo", jdbcType=JdbcType.VARCHAR)
    })
    List<OubShipmentDetail> selectAll();

    @Update({
        "update oub_shipment_detail",
        "set oub_shipment_header_id = #{oubShipmentHeaderId,jdbcType=BIGINT},",
          "shipment_no = #{shipmentNo,jdbcType=VARCHAR},",
          "shipment_line_no = #{shipmentLineNo,jdbcType=INTEGER},",
          "warehouse_code = #{warehouseCode,jdbcType=VARCHAR},",
          "status_code = #{statusCode,jdbcType=SMALLINT},",
          "erp_order_no = #{erpOrderNo,jdbcType=VARCHAR},",
          "erp_order_line_no = #{erpOrderLineNo,jdbcType=VARCHAR},",
          "item_code = #{itemCode,jdbcType=VARCHAR},",
          "item_name = #{itemName,jdbcType=VARCHAR},",
          "client_code = #{clientCode,jdbcType=VARCHAR},",
          "client_name = #{clientName,jdbcType=VARCHAR},",
          "inventory_type = #{inventoryType,jdbcType=VARCHAR},",
          "batch_no = #{batchNo,jdbcType=VARCHAR},",
          "inventory_quality = #{inventoryQuality,jdbcType=VARCHAR},",
          "country_of_origin = #{countryOfOrigin,jdbcType=VARCHAR},",
          "exp_date = #{expDate,jdbcType=DATE},",
          "mfg_date = #{mfgDate,jdbcType=DATE},",
          "received_date = #{receivedDate,jdbcType=DATE},",
          "po_no = #{poNo,jdbcType=VARCHAR},",
          "sales_no = #{salesNo,jdbcType=VARCHAR},",
          "sales_status = #{salesStatus,jdbcType=VARCHAR},",
          "inventory_status = #{inventoryStatus,jdbcType=BIT},",
          "brand_code = #{brandCode,jdbcType=VARCHAR},",
          "brand_name = #{brandName,jdbcType=VARCHAR},",
          "vendor_code = #{vendorCode,jdbcType=VARCHAR},",
          "vendor_name = #{vendorName,jdbcType=VARCHAR},",
          "req_qty = #{reqQty,jdbcType=DECIMAL},",
          "req_uom = #{reqUom,jdbcType=VARCHAR},",
          "orig_allocation_qty = #{origAllocationQty,jdbcType=DECIMAL},",
          "allocation_qty = #{allocationQty,jdbcType=DECIMAL},",
          "allocation_uom = #{allocationUom,jdbcType=VARCHAR},",
          "picked_qty = #{pickedQty,jdbcType=DECIMAL},",
          "picked_uom = #{pickedUom,jdbcType=VARCHAR},",
          "oqc_qty = #{oqcQty,jdbcType=DECIMAL},",
          "oqc_uom = #{oqcUom,jdbcType=VARCHAR},",
          "sorting_qty = #{sortingQty,jdbcType=DECIMAL},",
          "sorting_ep_qty = #{sortingEpQty,jdbcType=DECIMAL},",
          "sorting_uom = #{sortingUom,jdbcType=VARCHAR},",
          "oub_qty = #{oubQty,jdbcType=DECIMAL},",
          "oub_uom = #{oubUom,jdbcType=VARCHAR},",
          "oub_date = #{oubDate,jdbcType=TIMESTAMP},",
          "oub_user = #{oubUser,jdbcType=VARCHAR},",
          "priority = #{priority,jdbcType=VARCHAR},",
          "exception_type = #{exceptionType,jdbcType=VARCHAR},",
          "exception_desc = #{exceptionDesc,jdbcType=VARCHAR},",
          "exception_approach = #{exceptionApproach,jdbcType=VARCHAR},",
          "exception_qty = #{exceptionQty,jdbcType=DECIMAL},",
          "price = #{price,jdbcType=DECIMAL},",
          "item_retail_price = #{itemRetailPrice,jdbcType=DECIMAL},",
          "item_net_price = #{itemNetPrice,jdbcType=DECIMAL},",
          "req_weight = #{reqWeight,jdbcType=DECIMAL},",
          "weight_uom = #{weightUom,jdbcType=VARCHAR},",
          "item_class_code = #{itemClassCode,jdbcType=VARCHAR},",
          "is_gift = #{isGift,jdbcType=BIT},",
          "is_immediate_need = #{isImmediateNeed,jdbcType=BIT},",
          "ec_mode = #{ecMode,jdbcType=VARCHAR},",
          "req_volume = #{reqVolume,jdbcType=DECIMAL},",
          "req_volume_uom = #{reqVolumeUom,jdbcType=VARCHAR},",
          "brand_type = #{brandType,jdbcType=VARCHAR},",
          "channel_type = #{channelType,jdbcType=VARCHAR},",
          "fulfillment_type = #{fulfillmentType,jdbcType=VARCHAR},",
          "item_size = #{itemSize,jdbcType=VARCHAR},",
          "package_code = #{packageCode,jdbcType=VARCHAR},",
          "package_name = #{packageName,jdbcType=VARCHAR},",
          "return_max_uom = #{returnMaxUom,jdbcType=VARCHAR},",
          "return_max_qty = #{returnMaxQty,jdbcType=DECIMAL},",
          "oqc_itemscan_field1 = #{oqcItemscanField1,jdbcType=VARCHAR},",
          "oqc_itemscan_value1 = #{oqcItemscanValue1,jdbcType=VARCHAR},",
          "oqc_itemscan_field2 = #{oqcItemscanField2,jdbcType=VARCHAR},",
          "oqc_itemscan_value2 = #{oqcItemscanValue2,jdbcType=VARCHAR},",
          "oqc_column_field1 = #{oqcColumnField1,jdbcType=VARCHAR},",
          "oqc_column_value1 = #{oqcColumnValue1,jdbcType=VARCHAR},",
          "oqc_column_field2 = #{oqcColumnField2,jdbcType=VARCHAR},",
          "oqc_column_value2 = #{oqcColumnValue2,jdbcType=VARCHAR},",
          "oqc_itemdesc_value1 = #{oqcItemdescValue1,jdbcType=VARCHAR},",
          "oqc_itemdesc_value2 = #{oqcItemdescValue2,jdbcType=VARCHAR},",
          "no_po = #{noPo,jdbcType=SMALLINT},",
          "en_company_desc = #{enCompanyDesc,jdbcType=VARCHAR},",
          "en_item_desc = #{enItemDesc,jdbcType=VARCHAR},",
          "gross_weight = #{grossWeight,jdbcType=DECIMAL},",
          "sale_brand_id = #{saleBrandId,jdbcType=VARCHAR},",
          "reserved_qty = #{reservedQty,jdbcType=DECIMAL},",
          "inv_lot_id = #{invLotId,jdbcType=BIGINT},",
          "lot_attr1 = #{lotAttr1,jdbcType=VARCHAR},",
          "lot_attr2 = #{lotAttr2,jdbcType=VARCHAR},",
          "lot_attr3 = #{lotAttr3,jdbcType=VARCHAR},",
          "lot_attr4 = #{lotAttr4,jdbcType=VARCHAR},",
          "lot_attr5 = #{lotAttr5,jdbcType=VARCHAR},",
          "lot_attr6 = #{lotAttr6,jdbcType=VARCHAR},",
          "lot_attr7 = #{lotAttr7,jdbcType=VARCHAR},",
          "lot_attr8 = #{lotAttr8,jdbcType=VARCHAR},",
          "lot_attr9 = #{lotAttr9,jdbcType=DECIMAL},",
          "lot_attr10 = #{lotAttr10,jdbcType=DECIMAL},",
          "lot_attr11 = #{lotAttr11,jdbcType=DECIMAL},",
          "lot_attr12 = #{lotAttr12,jdbcType=DECIMAL},",
          "lot_attr13 = #{lotAttr13,jdbcType=DATE},",
          "lot_attr14 = #{lotAttr14,jdbcType=DATE},",
          "lot_attr15 = #{lotAttr15,jdbcType=DATE},",
          "lot_attr16 = #{lotAttr16,jdbcType=DATE},",
          "user_def1 = #{userDef1,jdbcType=VARCHAR},",
          "user_def2 = #{userDef2,jdbcType=VARCHAR},",
          "user_def3 = #{userDef3,jdbcType=VARCHAR},",
          "user_def4 = #{userDef4,jdbcType=VARCHAR},",
          "user_def5 = #{userDef5,jdbcType=VARCHAR},",
          "user_def6 = #{userDef6,jdbcType=VARCHAR},",
          "user_def7 = #{userDef7,jdbcType=TIMESTAMP},",
          "user_def8 = #{userDef8,jdbcType=TIMESTAMP},",
          "user_def9 = #{userDef9,jdbcType=DECIMAL},",
          "user_def10 = #{userDef10,jdbcType=DECIMAL},",
          "goods_line_money = #{goodsLineMoney,jdbcType=DECIMAL},",
          "from_warehouse_code = #{fromWarehouseCode,jdbcType=VARCHAR},",
          "goods_pic = #{goodsPic,jdbcType=VARCHAR},",
          "created_by_user_id = #{createdByUserId,jdbcType=BIGINT},",
          "created_by_user = #{createdByUser,jdbcType=VARCHAR},",
          "created_office = #{createdOffice,jdbcType=VARCHAR},",
          "created_dtm_loc = #{createdDtmLoc,jdbcType=TIMESTAMP},",
          "created_time_zone = #{createdTimeZone,jdbcType=VARCHAR},",
          "updated_by_user_id = #{updatedByUserId,jdbcType=BIGINT},",
          "updated_by_user = #{updatedByUser,jdbcType=VARCHAR},",
          "updated_office = #{updatedOffice,jdbcType=VARCHAR},",
          "updated_dtm_loc = #{updatedDtmLoc,jdbcType=TIMESTAMP},",
          "updated_time_zone = #{updatedTimeZone,jdbcType=VARCHAR},",
          "record_version = #{recordVersion,jdbcType=BIGINT},",
          "container_code = #{containerCode,jdbcType=VARCHAR},",
          "owner_code = #{ownerCode,jdbcType=VARCHAR},",
          "sales_type_flag = #{salesTypeFlag,jdbcType=TINYINT},",
          "not_allow_return = #{notAllowReturn,jdbcType=TINYINT},",
          "inventory_group = #{inventoryGroup,jdbcType=TINYINT},",
          "serial_no = #{serialNo,jdbcType=VARCHAR}",
        "where oub_shipment_detail_id = #{oubShipmentDetailId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OubShipmentDetail record);
}